# Generated by Django 4.2.2 on 2023-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('weather_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
